image: node

stages:
  - test
  - package
  - deploy
  
before_script:
  - whoami
  - pwd

test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
    
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://vitops-rc.surge.sh --timeout 90000
    - blc --recursive --exclude-external http://vitops-rc.surge.sh
    
vulnerabilities check:
  stage: test
  script:
    - cd website && npm install && npm run scan
    
package site:
  stage: package
  cache:
    key: site-package
    policy: push
    paths:
      - /builds/victorrgds/devops/website
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - ./website/build/
    
  script:
    - cd website
    - npm install
    - npm run build
    
deploy to develop:
  stage: deploy
  variables:
    CNAME: develop-vitops.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/devops --domain ${CNAME}
  after_script:
    - pwd
  environment:
    name: develop
    url: http://${CNAME}
  only:
    - develop
    
deploy to release:
  stage: deploy
  variables:
    CNAME: $CI_COMMIT_REF_SLUG.vitops.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/devops --domain ${CNAME}
  after_script:
    - pwd
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}
    on_stop: turnoff
  only:
    - /^release-.*$/
  
turnoff:
  stage: deploy
  variables:
    CNAME: $CI_COMMIT_REF_SLUG.vitops.surge.sh
    GIT_STRATEGY: none  
  before_script:
    - npm install -g surge
  script:
    - surge teardown ${CNAME}
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}
    action: stop
  only:
    - /^release-.*$/
  
deploy to production:
  stage: deploy
  variables:
    CNAME: vitops.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/devops --domain ${CNAME}
  after_script:
    - pwd
  environment:
    name: production
    url: http://${CNAME}
  only:
    - master
